services:
  mysql:
    image: mysql:8.0
    container_name: mysql-project
    environment:
      MYSQL_ROOT_PASSWORD: project
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
      MYSQL_TCP_PORT: 3307
    volumes:
      - mysqlvolume:/var/lib/mysql
      - ./custom-my.cnf:/etc/mysql/my.cnf
    ports:
      - "3307:3307"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysqlvolume: